[project]
name = "easytype"
version = "0.1.0"
description = "Mobile input to Windows clipboard or direct typing"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.0",
    "pyautogui>=0.9.54",
    "pyinstaller>=6.17.0",
    "pyperclip>=1.8.2",
    "pystray>=0.19.5",
    "pillow>=10.0.0",
]

[project.scripts]
easytype = "main:main"
